name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 0.2.8
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  ffmpeg_kit_flutter_new_min: ^2.1.0
  video_player: ^2.2.7
  video_thumbnail: 0.5.3
  path_provider: ^2.0.7
  intl: any
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
